### ISSUE TITLE
OrderBy

### ISSUE THREAD

**Issue by juankDevelop** [doncicuto/es-provinces#1]
Hola!

Me gustaría saber si hay posibilidad de ordenar las provincias alfabeticamente

Un saludo.

**Comment by doncicuto** [comment]
Hola @juankDevelop,
claro puedes ordenar las provincias con javascript, sólo hay que tener cuidado para que la ordenación tenga en cuenta los acentos:

```
const sortered = provinces.map((p) => p.name).sort(function (a, b) {
  return a.localeCompare(b);
})
console.log(sortered);

```

Esto devolvería:

```
[
  'A Coruña',          'Albacete',      'Alicante/Alacant',
  'Almería',           'Araba/Álava',   'Asturias',
  'Ávila',             'Badajoz',       'Barcelona',
  'Bizkaia',           'Burgos',        'Cáceres',
  'Cádiz',             'Cantabria',     'Castellón/Castelló',
  'Ceuta',             'Ciudad Real',   'Córdoba',
  'Cuenca',            'Gipuzkoa',      'Girona',
  'Granada',           'Guadalajara',   'Huelva',
  'Huesca',            'Illes Balears', 'Jaén',
  'La Rioja',          'Las Palmas',    'León',
  'Lleida',            'Lugo',          'Madrid',
  'Málaga',            'Melilla',       'Murcia',
  'Navarra',           'Ourense',       'Palencia',
  'Pontevedra',        'Salamanca',     'Santa Cruz de Tenerife',
  'Segovia',           'Sevilla',       'Soria',
  'Tarragona',         'Teruel',        'Toledo',
  'Valencia/València', 'Valladolid',    'Zamora',
  'Zaragoza'
]
```

¿Puede valerte?

**Comment by juankDevelop** [comment]
Hola!

Actualmente estoy usando  React, sabrías como hacerlo teniendo en cuenta lo que me dices?
aunque bueno, imagino que será algo similar no?

Un saludo y muchas gracias.


Juan Camilo Amaya Florez
Departamento de Soporte
***@***.******@***.***>
grupolae.net<https://outlook.office.com/local/path/file:///Applications/Microsoft%20Outlook.app/Contents/Frameworks/EmailRendererKit.framework/Resources/grupolae.net>

[Image]

[Image]<https://www.linkedin.com/company/5253243>  [Image] <https://twitter.com/grupo_lae>   [Image] <https://www.instagram.com/grupo_lae>   [Image] <https://www.facebook.com/grouplae/>   [Image] ***@***.***>

La información contenida en este mensaje y/o archivo(s) adjunto(s), enviada desde GRUPO LAE, es confidencial/privilegiada y está destinada a ser leída sólo por la(s) persona(s) a la(s) que va dirigida. Sus datos serán tratados por el Responsable del tratamiento: GRUPO LAE (el cual lo constituyen Lae Consulting normativas SL, con CIF B75010686 y Lae Formación Programada, S.L., con CIF B20910121 ambas con domicilio en C/ Juan F. Gilisagasti 2 – Oficina 215, 20018 Donostia – San Sebastián (Gipuzkoa). Finalidad: Los datos de contacto y en su caso los relativos a la función o puesto desempeñado de las personas físicas que presten servicios en la empresa serán tratados con la finalidad de mantener el contacto con las mismas, así como de llevar a cabo su localización profesional. Base de legitimación: Interés legítimo. Destinatarios: No se cederán datos a terceros salvo que sean estrictamente necesarios o exista una obligación legal. Plazo de conservación: Mientras que esté en vigor la relación entre las partes. Derechos: Puede ejercer sus Derechos de acceder, rectificar, oponerse, limitar, portar y suprimir los datos ante el responsable del tratamiento; además de acudir ante la autoridad competente si lo desea (AEPD).



Si usted lee este mensaje y no es el destinatario señalado, el empleado o el agente responsable de entregar el mensaje al destinatario, o ha recibido esta comunicación por error, le informamos que está totalmente prohibida, y puede ser ilegal, cualquier divulgación, distribución o reproducción de esta comunicación, y le rogamos que nos lo notifique inmediatamente y nos devuelva el mensaje original a la dirección arriba mencionada. Gracias.



[Image]

________________________________
De: Miguel Cabrerizo ***@***.***>
Enviado: viernes, 5 de abril de 2024 13:15
Para: doncicuto/es-provinces ***@***.***>
Cc: Juan Camilo Amaya ***@***.***>; Mention ***@***.***>
Asunto: Re: [doncicuto/es-provinces] OrderBy (Issue #1)


Hola @juankDevelop<https://github.com/juankDevelop>,
claro puedes ordenar las provincias con javascript, sólo hay que tener cuidado para que la ordenación tenga en cuenta los acentos:

const sortered = provinces.map((p) => p.name).sort(function (a, b) {
  return a.localeCompare(b);
})
console.log(sortered);



Esto devolvería:

[
  'A Coruña',          'Albacete',      'Alicante/Alacant',
  'Almería',           'Araba/Álava',   'Asturias',
  'Ávila',             'Badajoz',       'Barcelona',
  'Bizkaia',           'Burgos',        'Cáceres',
  'Cádiz',             'Cantabria',     'Castellón/Castelló',
  'Ceuta',             'Ciudad Real',   'Córdoba',
  'Cuenca',            'Gipuzkoa',      'Girona',
  'Granada',           'Guadalajara',   'Huelva',
  'Huesca',            'Illes Balears', 'Jaén',
  'La Rioja',          'Las Palmas',    'León',
  'Lleida',            'Lugo',          'Madrid',
  'Málaga',            'Melilla',       'Murcia',
  'Navarra',           'Ourense',       'Palencia',
  'Pontevedra',        'Salamanca',     'Santa Cruz de Tenerife',
  'Segovia',           'Sevilla',       'Soria',
  'Tarragona',         'Teruel',        'Toledo',
  'Valencia/València', 'Valladolid',    'Zamora',
  'Zaragoza'
]


¿Puede valerte?

**Comment by doncicuto** [comment]
Hola,
el código que te he puesto es javascript estándar y deberías poder usarlo sin problema en React, bastaría con hacer el import de la librería.

Saludos

**Comment by doncicuto** [comment]
Voy a cerrar el issue, si tienes más dudas o algo no funciona sólo tienes que reabrirla. Gracias por usar mi librería.

**Comment by juankDevelop** [comment]
Si, sin problemas, gracias a ti 🙂 nos ahorraste mucho trabajo


Juan Camilo Amaya Florez
Departamento de Soporte
***@***.******@***.***>
grupolae.net<https://outlook.office.com/local/path/file:///Applications/Microsoft%20Outlook.app/Contents/Frameworks/EmailRendererKit.framework/Resources/grupolae.net>

[Image]

[Image]<https://www.linkedin.com/company/5253243>  [Image] <https://twitter.com/grupo_lae>   [Image] <https://www.instagram.com/grupo_lae>   [Image] <https://www.facebook.com/grouplae/>   [Image] ***@***.***>

La información contenida en este mensaje y/o archivo(s) adjunto(s), enviada desde GRUPO LAE, es confidencial/privilegiada y está destinada a ser leída sólo por la(s) persona(s) a la(s) que va dirigida. Sus datos serán tratados por el Responsable del tratamiento: GRUPO LAE (el cual lo constituyen Lae Consulting normativas SL, con CIF B75010686 y Lae Formación Programada, S.L., con CIF B20910121 ambas con domicilio en C/ Juan F. Gilisagasti 2 – Oficina 215, 20018 Donostia – San Sebastián (Gipuzkoa). Finalidad: Los datos de contacto y en su caso los relativos a la función o puesto desempeñado de las personas físicas que presten servicios en la empresa serán tratados con la finalidad de mantener el contacto con las mismas, así como de llevar a cabo su localización profesional. Base de legitimación: Interés legítimo. Destinatarios: No se cederán datos a terceros salvo que sean estrictamente necesarios o exista una obligación legal. Plazo de conservación: Mientras que esté en vigor la relación entre las partes. Derechos: Puede ejercer sus Derechos de acceder, rectificar, oponerse, limitar, portar y suprimir los datos ante el responsable del tratamiento; además de acudir ante la autoridad competente si lo desea (AEPD).



Si usted lee este mensaje y no es el destinatario señalado, el empleado o el agente responsable de entregar el mensaje al destinatario, o ha recibido esta comunicación por error, le informamos que está totalmente prohibida, y puede ser ilegal, cualquier divulgación, distribución o reproducción de esta comunicación, y le rogamos que nos lo notifique inmediatamente y nos devuelva el mensaje original a la dirección arriba mencionada. Gracias.



[Image]

________________________________
De: Miguel Cabrerizo ***@***.***>
Enviado: miércoles, 10 de abril de 2024 7:04
Para: doncicuto/es-provinces ***@***.***>
Cc: Juan Camilo Amaya ***@***.***>; Mention ***@***.***>
Asunto: Re: [doncicuto/es-provinces] OrderBy (Issue #1)


Voy a cerrar el issue, si tienes más dudas o algo no funciona sólo tienes que reabrirla. Gracias por usar mi librería.
